version: "3.8"

services:
  vault:
    build: .
    container_name: secure-vault
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    environment:
      LD_LIBRARY_PATH: /usr/local/lib
      PKG_CONFIG_PATH: /usr/local/lib/pkgconfig:$HOME/liboqs-go/.config
